url: "https://guest."
username__Name: "username"
password__Name: "password"
accept_terms__Name: "visitor_accept_terms"
submit_button__Xpath: "//*[@id[contains(.,'weblogin_submit')]]"
wlan_name: "guest"
username: "x@y.z"
password: 012345
